server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: portal
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:portal_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=true&sslMode=REQUIRED
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never  # Default mode is never, use dev profile to enable initialization
      schema-locations: classpath:schema_complete.sql
      continue-on-error: true
      platform: mysql
  profiles:
    active: dev  # Set to 'dev' for development, 'prod' for production
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
  cache:
    type: redis  # Enable Redis caching
    redis:
      time-to-live: 3600000  # Default TTL: 1 hour (in milliseconds)
      cache-null-values: true
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mybatis:
  type-aliases-package: com.example.portal.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    '[com.example.portal]': DEBUG
    '[org.springframework.security]': INFO
    '[org.springframework.jdbc]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.springframework.data.redis]': DEBUG
    '[org.springframework.cache]': DEBUG
    '[io.lettuce.core]': INFO

# Application specific settings
app:
  email:
    enabled: false  # Set to true to enable email sending
  cache:
    use-redis: true  # Set to false to use in-memory cache instead of Redis
