server:
  port: 8080

spring:
  application:
    name: portal
  datasource:
    url: jdbc:mysql://localhost:3306/portal_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ydl11222004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      continue-on-error: true
      platform: mysql
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: none  # Disable caching
  security:
    user:
      name: admin
      password: admin123
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com  # Replace with your actual email if you want to enable email sending
    password: your-app-password     # Replace with your actual app password if you want to enable email sending
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mybatis:
  type-aliases-package: com.example.portal.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    '[com.example.portal]': DEBUG
    '[org.springframework.security]': INFO
    '[org.springframework.jdbc]': DEBUG
    '[org.hibernate.SQL]': DEBUG

# Application specific settings
app:
  email:
    enabled: false  # Set to true to enable email sending
